spring.application.name=arcade-manager-api

spring.data.mongodb.uri=mongodb://localhost:27017/arcade-manager
spring.data.mongodb.database=arcade-manager

server.port=8080

spring.jackson.serialization.write-dates-as-timestamps=false
