
spring.application.name=arcade-manager-api
server.port=8080
server.address=0.0.0.0

spring.mongodb.database=arcade-manager
spring.mongodb.uri=mongodb://localhost:27017

spring.jackson.default-property-inclusion=NON_NULL


logging.level.org.springframework=INFO
logging.level.com.wagnerdf.arcademanager=DEBUG

spring.security.user.name=admin
spring.security.user.password=admin123

rawg.api.key=${RAWG_API_KEY}